// Regenerates presets.js from the append-only artifact registry in runs/.
// Every artifact is self-contained: knots plus the full plant/controller
// config, ROM, and strength it was produced under. Replays use the
// artifact's own config, so adopting new defaults never rewrites history;
// forward progress appends new artifacts and updates the manifest.
//
// Usage: node scripts/build-presets.mjs   (reads runs/manifest.json)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const runsDir = join(root, 'runs');
const manifest = JSON.parse(readFileSync(join(runsDir, 'manifest.json'), 'utf8'));
const load = (f) => JSON.parse(readFileSync(join(runsDir, f), 'utf8'));

const round = (x) => (typeof x === 'number' ? +x.toPrecision(6) : x);
const roundDeep = (o) => JSON.parse(JSON.stringify(o, (k, v) => round(v)));
const normStrength = (s) => (s ? (s.overrides || s) : undefined);

function entry(file, label) {
  const j = load(file);
  return {
    file,
    label: label || j.label || file,
    scenario: j.scenario,
    rom: j.rom || null,
    strength: normStrength(j.strength) || null,
    config: j.config || null,
    weights: j.weights || null,
    seed: j.seed ?? null,
    T: j.T,
    knots: j.knots,
    recordedCost: j.fineCost,
    verdict: j.verdict,
  };
}

const trajectories = {};
for (const [key, file] of Object.entries(manifest.presets)) {
  trajectories[key] = entry(file);
}
const gallery = manifest.gallery.map((g) => entry(g.file, g.label));
const catchGrid = manifest.catch ? load(manifest.catch) : null;

const body = `// Generated by scripts/build-presets.mjs from the append-only artifact
// registry in runs/ (see runs/manifest.json). Each entry carries the full
// plant/controller config it was produced under; replays must use it.
export const PRESET_TRAJECTORIES = ${JSON.stringify(roundDeep(trajectories), null, 1)};

export const PRESET_CATCH_WINDOW = ${JSON.stringify(catchGrid ? roundDeep(catchGrid) : null)};

export const PRESET_SWEEPS = [];

export const PRESET_GALLERY = ${JSON.stringify(roundDeep(gallery), null, 1)};
`;

writeFileSync(join(root, 'presets.js'), body);
console.log(`wrote presets.js: ${Object.keys(trajectories).length} presets, ${gallery.length} gallery artifacts`);
