export const TILE_URL_TERRAIN = __TILE_URL_TERRAIN__;
export const TILE_URL_SENTINEL = __TILE_URL_SENTINEL__;
export const TILE_URL_TAHOE = __TILE_URL_TAHOE__;
export const TILE_URL_TAHOE_SENTINEL = __TILE_URL_TAHOE_SENTINEL__;
