[menu fullWidth:true/]

[meta title:"The Unreasonable Beauty of Guided Waves" fullWidth:true/]

[header
  title:"The Unreasonable Beauty of Guided Waves"
  author:"Ricky Reusser"
  authorUrl:"https://rreusser.github.io"
  fullWidth:true
  date:"March 18, 2018"
/]

## A preface on Big Data

We've come to understand that the halcyon days of the Big Data Revolution warmed up our web scrapers just in time for the Machine Learning Revolution that's now upon us. With enough data, we can solve previously-intractible problems. Cat recognition yesterday, self-driving cars today, everything tomorrow. Distilling [The Unreasonable Effectiveness of Data](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/35179.pdf) to a pithy quote, Google Research Director Peter Norvig says, "[We don't have better algorithms. We just have more data.](https://www.cnet.com/news/tim-oreilly-whole-web-is-the-os-of-the-future/)" Prepare to behold the [beautiful](https://sites.google.com/view/aiandsocialgood/) and [terrible](https://www.nytimes.com/2018/03/04/technology/fake-videos-deepfakes.html) future.

I'm going to start with a confession: I'm just not that into it.

Many reasons, I'm sure. I feel the reasons gnawing away in my subconscious every time I star a [style transfer repo](https://github.com/fzliu/style-transfer). I'm sure it's driven by ignorance and that I'll benefit in ways I never expected and perhaps won't even realize. I'm sure Google's auto-addition of calendar events will get better. I'm sure I'm a dinosaur already, that we'll tame the ugliness, and that for my disbelief, the profound beauty of something I hold dear will be the next thing squeezed through [machine learning's wringer](https://www.quantamagazine.org/new-theory-cracks-open-the-black-box-of-deep-learning-20170921/).

I like to tell myself that we can all just live in harmony, that the future will be great, and that I simply have other interests. [But I do wonder](https://www.google.com/search?q=christopher+wylie).

And so, having brought this angst to the table, I'm simply going to take a left turn and delve into a topic which I always found surprisingly—for lack of a more… whatever, I don't know… term—beautiful.

## The allure of Small Data

Fluid flow is a scientific field generally accepted as "beautiful." See for yourself at the [Gallery of Fluid Motion](https://gfm.aps.org).

Wow! If you're like me and you've been browsing videos of direct numerical simulation of turbulence for the last twenty minutes, you need no further convincing. Thanks for coming back!

It certainly pulled me in. Life has its way of happening though, and so I found myself in grad school researching in Ultrasonic Non-Destructive Evaluation (NDE).



[footer fullWidth:true/]
