[menu fullWidth:true/]

[meta
  title:"Trails and Trains Part 1: Berkeley to Orinda via EBMUD Watershed Trails"
  fullWidth:true
/]

[Header
  title:"Trails and Trains Part 1: Berkeley to Orinda via EBMUD Watershed Trails"
  author: "Ricky Reusser"
  authorLink: "https://github.com/rreusser"
  date: "July 15, 2021"
  fullWidth:true
  bgImageSrc:"static/IMG_0224.jpg"
/]

This post is the first in a series with a simple premise: I love trail running and plan to explore the spectrum of trail running accessible strictly via public transportation.

So let's first set the ground rules. Cars are out. (Maybe someday everywhere, categorically. Fingers crossed.) The run must include at least some form of public transportation, whether train, bus, or otherwise. I'll rate the runs on the following dimensions:

- **Accessibility**: How long, expensive, or pleasant is the commute?
- **Hilliness**: If we're trail running, we should hope for some hills.
- **Nature**: I'll start all journeys in downtown Oakland, California, so a primary goal is to see some trees and animals. Bonus points if there's no cell service.


## Getting there






[footer fullWidth:true/]
