[menu fullWidth:true/]

[meta fullWidth:true
  title:"Multi-Scale Turing Patterns"
  description:"A gallery of multi-scale Turing patterns"
  shareImageUrl:"https://raw.githubusercontent.com/rreusser/rreusser.github.io/master/src/src/multiscale-turing-pattern-gallery/images/ogimage.jpg"
  twitterHandle:"rickyreusser"
/]

[header
  fullWidth:true
  title:"Multi-Scale Turing Patterns"
  author: "Ricky Reusser"
  authorLink: "https://twitter.com/rickyreusser"
  date: "October 19, 2018"
  bgImageSrc:"static/header.jpg"
/]

This page contains a gallery of multi-scale [Turing patterns](https://en.wikipedia.org/wiki/Turing_pattern). The method is a single-variable simulation of a [reaction-diffusion system](https://en.wikipedia.org/wiki/Reaction%E2%80%93diffusion_system) which approximates diffusion through circular convolutions. The multi-scale extension switches between Turing patterns at different scales based on local properties. The images below implement Jason Rampe's blog post [Multi-Scale Turing Patterns](https://softologyblog.wordpress.com/2011/07/05/multi-scale-turing-patterns/) in which he describes with excellent clarity the algorithm previously described by [Jonathan McCabe](http://www.jonathanmccabe.com/) in his paper, [Cyclic Symmetric Multi-Scale Turing Patterns](http://www.jonathanmccabe.com/Cyclic_Symmetric_Multi-Scale_Turing_Patterns.pdf). (Both an indespensible read if you want to explore these patterns further!)

You can view a live implementation with which the images on this page were computed [here](http://rreusser.github.io/multiscale-turing-patterns/), and you can find the source of the implementation [here](https://github.com/rreusser/rreusser.github.io/tree/a3ee324f82794e7be632038fd218ca38ae91d27b/src/src/multiscale-turing-patterns). The simulation is computed in WebGL using the (outstanding!) [regl](https://github.com/regl-project/regl) library. (I love regl, but that's a topic for [another post](http://rreusser.github.io/from-nothing-to-something-in-webgl-with-regl/)).  The implementation is not currently configurable on the web—though I would love for it to be!

Most of the images below are computed at 4096 x 4096 pixels, which is the limit of the size my poor laptop can manage before the system grinds to a halt. Each image takes thirty minutes or so to compute. Using periodicity, they're extended horizontally to 6144 pixels wide so that they fit on a horizontal screen.  For the convolutions, it uses my own [GLSL implementation](https://github.com/rreusser/glsl-fft) of the Fast Fourier Transform, which is in turn a refactoring of [David Li's FFT implementation](http://david.li/filtering/). I found when trying out parameters that very slightly negative weights produce a wonderful effect in coloring detail (as seen in the first two images).

Based on my approach to coloring, I'm thrilled that Jason has also tried it out and since added coloring to his method and blog post. I heartily second his encouragement to try things out, let people know when their work is helpful, and seek out collaboration! 🎉

[Gallery
  fullWidth:true
  basePath:"https://s3.amazonaws.com/images.rickyreusser.com/multiscale-turing-patterns/"
  contents:`[
    {href:"turing01.jpg"},
    {href:"turing02.jpg"},
    {href:"turing03.jpg"},
    {href:"turing04.jpg"},
    {href:"turing05.jpg"},
    {href:"turing06.jpg"},
    {href:"turing07.jpg"},
    {href:"turing08.jpg"},
    {href:"turing09.jpg"},
    {href:"turing10.jpg"},
    {href:"turing11.jpg"},
    {href:"turing12.jpg"},
    {href:"turing13.jpg"},
    {href:"turing14.jpg"},
  ]`
/]

[a rel:"license" href:"http://creativecommons.org/licenses/by-nc/4.0/"][img alt:"Creative Commons License" style:`{borderWidth:"0"}` src:"https://i.creativecommons.org/l/by-nc/4.0/88x31.png"/][/a][br/]This work is licensed under a [a rel:"license" href:"http://creativecommons.org/licenses/by-nc/4.0/"]Creative Commons Attribution-NonCommercial 4.0 International License[/a].

[small]
(Realistically, shoot me a message at [@rickyreusser](https://twitter.com/rickyreusser) and I'd probably let you do just about anything with these images or my implementation which generates them, but I've made the code and high resolution originals (well, compressed to jpeg—let me know if you want a 30MB png) available out of good will and good intentions, and since I'm deeply indebted to the people whose work has enabled me to create these, I've licensed these explicitly only as a small step beyond simply asking politely that you not, like, find some way I don't even know exists and turn around and sell them for profit or something. ❤️)
[/small]

[footer fullWidth:true/]
