[menu fullWidth:true/]

[meta fullWidth:true title:"Projects"/]

[Header
  fullWidth:true
  title:"Projects"
/]

A set of experirments and explorations, mostly using the [regl](https://github.com/regl-project/regl) WebGL library, some computed on the GPU and some on the CPU. The source for all content and projects on this site can be found [here](https://github.com/rreusser/rreusser.github.io/tree/master/src/src). Keep in mind though that these are explorations and that I certainly learned as much (often more) about how *not* to approach these projects as about how *to* approach these projects.

Comments? Questions? Let me know [@rickyreusser](https://twitter.com/rickyreusser).

[ProjectIndex fullWidth:true/]

[footer fullWidth:true/]
