[meta title:"Unnecessarily Optimized Gamma Correction" description:"Polynomial approximations for gamma correction" /]

[Header
  title:"Unnecessarily Optimized Gamma Correction"
  subtitle:"Polynomial approximations for gamma correction"
  author:"Ricky Reusser"
  authorLink:"http://github.com/rreusser/" /]

Gamma correction is a standard technique in computer graphics. In short, monitors don't display colors linearly so that it falls upon the developer to apply corrections so that colors are displayed correctly. If you're not familiar with gamma correction, [Gamma Correction and Why It Matters](https://gamedevelopment.tutsplus.com/articles/gamma-correction-and-why-it-matters--gamedev-14466) is an excellent introduction to the subject.

In this article though, I'll assume you *are* familiar with gamma correction.

[Equation]
y = x^2
[/Equation]
