[menu fullWidth:true/]

[meta fullWidth:true title:"Reading"/]

[Header
  fullWidth:true
  title:"Reading"
  bgImageSrc:"images/books.jpg"
	bgImagePreviewSrc:"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAASACADAREAAhEBAxEB/8QAGQABAAIDAAAAAAAAAAAAAAAABAECAwUG/8QAKxAAAgEDAgMGBwAAAAAAAAAAAQIDAAQREiEFMUETI1FzgbEUIjIzY3Hw/8QAGgEAAgMBAQAAAAAAAAAAAAAAAgMABAUBBv/EACERAAICAgEEAwAAAAAAAAAAAAABAhEhMRIDIkFxMlGx/9oADAMBAAIRAxEAPwDlJJ7p7hpmuIy7bA9nsD+s1nuS+j0CU0uKePRey7aS5hRWgDGYAFlYkE7550Tl20Zko9zYfiSz2THvIpPifmI0kY1etdhLkC40jVoZpMQq6aTk7g9M1cgsCJvLEqbYpoaHLBhnHh/Yqs07NFvp8dZG2z25h1o+mTCmPDkENtyx1pcrtCN2Qy2bPm9kyulQrmVsjnsCfDlUz4ONIEqrFbIkkPeSKSpwCT60ebu8COVow2gDcQiU7guuQeu4pj0WJbLWv1QD8i+4pbJ4GTqDwyTIBwpO/mUC2R6KT/fsvJb3ail8X7X6U4eD/9k="
/]


A list of books read in recent history, though it's been a rough couple years for actually finishing books. My commentary and opinions ommitted.

[book
  title:"The Visual Display of Quantitative Information"
  url:"https://www.edwardtufte.com/tufte/books_vdqi"
  author:"Edward R. Tufte"
  dateRead:"03-2018"
/]

[book
  title:"The Gulag Archipelago, 1918-1956: An Experiment in Literary Investigation I-II"
  url:"https://www.amazon.com/gp/product/0060139145"
  author:"Aleksandr Solzhenitsyn"
  dateRead:"03-2018"
/]

[book
  title:"Great Russian Short Stories of the Twentieth Century"
  url:"http://store.doverpublications.com/048648873x.html"
  author:"Yelena Francis (editor)"
  dateRead:"01-2018"
/]

[book
  title:"Polygon Mesh Processing"
  url:"https://www.crcpress.com/Polygon-Mesh-Processing/Botsch-Kobbelt-Pauly-Alliez-Levy/p/book/9781568814261"
  author:"Mario Botsch, Leif Kobbelt, Mark Pauly, Pierre Alliez, Bruno Levy"
  dateRead:"12-2017"
/]

[book
  title:"Is Journalism Worth Dying For?: Final Dispatches"
  url:"https://www.mhpbooks.com/books/is-journalism-worth-dying-for/"
  author:"Anna Politkovskaya"
  dateRead:"10-2017"
/]

[book
  title:"Secondhand Time: The Last of the Soviets"
  url:"https://www.penguinrandomhouse.com/books/541184/secondhand-time-by-svetlana-alexievich/9780399588822/"
  author:"Svetlana Alexievich"
  dateRead:"07-2017"
/]

[book
  title:"Pale Fire"
  url:"https://www.amazon.com/Pale-Fire-Vladimir-Nabokov/dp/0679723420"
  author:"Vladimir Nabokov"
  dateRead:"07-2016"
/]

[book
  title:"The Lottery and Other Stories"
  url:"https://www.penguin.co.uk/books/133428/the-lottery-and-other-stories/"
  author:"Shirley Jackson"
  dateRead:"05-2016"
/]

[book
  title:"Perestroika: New Thinking for Our Country and the World"
  url:"https://www.amazon.com/Perestroika-New-Thinking-Country-World/dp/0060390859"
  author:"Mikhail Gorbachev"
  dateRead:"04-2016"
/]

[book
  title:"Number Theory"
  url:"http://store.doverpublications.com/0486682528.html"
  author:"George E. Andrews"
  dateRead:"04-2016"
/]

[book
  title:"Sri Lanka—Ethnic Fratricide and the Dismantling of Democracy"
  url:"http://press.uchicago.edu/ucp/books/book/chicago/S/bo5960167.html"
  author:"Stanley Jeyaraja Tambiah"
  dateRead:"04-2016"
/]

[footer fullWidth:true/]
