[menu fullWidth:true/]

[meta fullWidth:true title:"Reading"/]

[Header
  fullWidth:true
  title:"Reading"
  bgImageSrc:"images/books.jpg"
/]


A list of books read in recent history. My commentary and opinions omitted.

[book
  title:"Educated"
  url:"https://tarawestover.com/book"
  author:"Tara Westover"
  dateRead:"04-2019"
/]

[book
  title:"The Gulag Archipelago, 1918-1956: An Experiment in Literary Investigation III-IV"
  url:"https://www.amazon.com/Gulag-Archipelago-Experiment-Investigation-Solzhenitsyn/dp/B019TL8JNK"
  author:"Aleksandr Solzhenitsyn"
  dateRead:"03-2019"
/]

[book
  title:"Sadako and the Thousand Paper Cranes"
  url:"https://en.wikipedia.org/wiki/Sadako_and_the_Thousand_Paper_Cranes"
  author:"Eleanor Coerr"
  dateRead:"01-2019"
/]

[book
  title:"The Line Becomes a River: Dispatches from the Border"
  url:"https://www.penguinrandomhouse.com/books/555764/the-line-becomes-a-river-by-francisco-cantu/"
  author:"Fransisco Cantú"
  dateRead:"01-2019"
/]

[book
  title:"An Island Hell"
  url:"https://archive.org/details/1926AnIslandHellMalsagoff/page/n1"
  author:"S.A. Malsagoff"
  dateRead:"10-2018"
/]

[book
  title:"Rules for Radicals"
  url:"https://archive.org/stream/RulesForRadicals/RulesForRadicals_djvu.txt"
  author:"Saul Alinsky"
  dateRead:"10-2018"
/]

[book
  title:"Hillbilly Elegy"
  url:"https://www.amazon.com/Hillbilly-Elegy-Memoir-Family-Culture/dp/0062300547"
  author:"J. D. Vance"
  dateRead:"10-2018"
/]

[book
  title:"A Scanner Darkly"
  url:"https://www.amazon.com/Scanner-Darkly-Philip-K-Dick/dp/0547572174"
  author:"Philip K. Dick"
  dateRead:"08-2018"
/]

[book
  title:"The Orphan Master's Son"
  url:"https://www.penguinrandomhouse.com/books/212862/the-orphan-masters-son-by-adam-johnson/9780812982626/"
  author:"Adam Johnson"
  dateRead:"08-2018"
/]

[book
  title:"Metal by Example"
  url:"http://metalbyexample.com/"
  author:"Warren Moore"
  dateRead:"07-2018"
/]

[book
  title:"Khrushchev: A Political Portrait"
  url:"https://www.amazon.com/Khrushchev-Political-Portrait-Konrad-Kellen/dp/B0000CL4OJ"
  author:"Konrad Kellen"
  dateRead:"06-2018"
/]

[book
  title:"Lincoln in the Bardo"
  url:"http://www.georgesaundersbooks.com/lincoln-in-the-bardo/"
  author:"George Saunders"
  dateRead:"05-2018"
/]

[book
  title:"The Visual Display of Quantitative Information"
  url:"https://www.edwardtufte.com/tufte/books_vdqi"
  author:"Edward R. Tufte"
  dateRead:"03-2018"
/]

[book
  title:"Number9Dream"
  url:"https://www.penguinrandomhouse.com/books/115432/number9dream-by-david-mitchell/9780812966923/"
  author:"David Mitchell"
  dateRead:"04-2018"
/]

[book
  title:"The Gulag Archipelago, 1918-1956: An Experiment in Literary Investigation I-II"
  url:"https://www.amazon.com/gp/product/0060139145"
  author:"Aleksandr Solzhenitsyn"
  dateRead:"03-2018"
/]

[book
  title:"Great Russian Short Stories of the Twentieth Century"
  url:"http://store.doverpublications.com/048648873x.html"
  author:"Yelena Francis (editor)"
  dateRead:"01-2018"
/]

[book
  title:"Polygon Mesh Processing"
  url:"https://www.crcpress.com/Polygon-Mesh-Processing/Botsch-Kobbelt-Pauly-Alliez-Levy/p/book/9781568814261"
  author:"Mario Botsch, Leif Kobbelt, Mark Pauly, Pierre Alliez, Bruno Levy"
  dateRead:"12-2017"
/]

[book
  title:"Is Journalism Worth Dying For?: Final Dispatches"
  url:"https://www.mhpbooks.com/books/is-journalism-worth-dying-for/"
  author:"Anna Politkovskaya"
  dateRead:"10-2017"
/]

[book
  title:"Secondhand Time: The Last of the Soviets"
  url:"https://www.penguinrandomhouse.com/books/541184/secondhand-time-by-svetlana-alexievich/9780399588822/"
  author:"Svetlana Alexievich"
  dateRead:"07-2017"
/]

[book
  title:"Pale Fire"
  url:"https://www.amazon.com/Pale-Fire-Vladimir-Nabokov/dp/0679723420"
  author:"Vladimir Nabokov"
  dateRead:"07-2016"
/]

[book
  title:"The Lottery and Other Stories"
  url:"https://www.penguin.co.uk/books/133428/the-lottery-and-other-stories/"
  author:"Shirley Jackson"
  dateRead:"05-2016"
/]

[book
  title:"Perestroika: New Thinking for Our Country and the World"
  url:"https://www.amazon.com/Perestroika-New-Thinking-Country-World/dp/0060390859"
  author:"Mikhail Gorbachev"
  dateRead:"04-2016"
/]

[book
  title:"Number Theory"
  url:"http://store.doverpublications.com/0486682528.html"
  author:"George E. Andrews"
  dateRead:"04-2016"
/]

[book
  title:"Sri Lanka—Ethnic Fratricide and the Dismantling of Democracy"
  url:"http://press.uchicago.edu/ucp/books/book/chicago/S/bo5960167.html"
  author:"Stanley Jeyaraja Tambiah"
  dateRead:"04-2016"
/]

[footer fullWidth:true/]
