[menu fullWidth:true/]

[meta
  title:"Some Piano Songs you Find Intersting"
  description:"Responding to a simple question"
  fullWidth:true
/]

[Header
  title: '"Some Piano Songs you Find Interesting"'
  author: "Ricky Reusser"
  authorLink: "https://github.com/rreusser"
  date: "March 10, 2024"
  fullWidth:true
/]

Upon learning I'd started piano lessons, a friend recently requested, "Send me some piano songs you find interesting." A simple enough request; no one, even I myself, could have foreseen it would leave me dangling above the abyss, on one hand appreciating that when it comes to taste in music, we're all ships with our own peculiar interests passing in the night, on the other hand that I struggle to rationalize or justify my own taste in music.

## In the beginning

[footer fullWidth:true/]
