[menu fullWidth:true/]

[meta fullWidth:true title:"Running"/]

[Header
  title: "Running"
  fullWidth:true
  bgImageSrc:"images/CO2016-37.jpg"
/]

### 8/15/18

[img src:"images/freycinet.jpg" alt:"Running"/]

Well we obviously haven't done a good job of logging the running here. We've had some pretty great runs and as much as a couple weeks without really much running at all. This hasn't been going according to plan, but then I guess the plan wasn't really to stick to a rigorous plan.

But yesterday? Yesterday was the first workout on a track in a long time. 10:19 for two miles (5:11-5:08). I'm a bit sore today but glad to know I can still move around a track at an alright speed. Going to try to repeat that soon.

### 4/5/18

2 x mile + 1 x 400. Short workout. 5:18, 5:15, 66. Feeling better than I thought maybe, but still not feeling particularly fast or effortless. Lots of work ahead if the Achilles will play along. 7 miles total.

### 4/3/18

3.17 mile tempo in 17:48 for an average pace of 5:36/mi. 4.75 miles total. Not bad. Good route. Room for consistent repetition and improvement.

### 4/1/18

6 mile hike. +/- 2400 ft.

### 3/31/18

5.5 miles. 3 x 1 mile on the track with 1:30 rest. 5:16, 5:17, 5:05. First thing approaching a workout in a long time. Nothing gets the lead out quite like the last 400m of your mile repeats coinciding with the first 600m of a high school team's workout. Didn't feel effortless, but maybe there's hope.

### 3/30/18

6.67 miles. Hill loop. 1845 ft up and down. 55:04 total. 24:25 up, 30:39 down.

### 3/29/18

8 miles. Moderate run with one mile on the track in the middle of the run. 5:17 (80-81-79-77). Felt tough. Knew getting the train started wasn't gonna be pleasant.

### 3/28/18

[img src:"images/el1.png" alt:"Elevation profile"/]

_Morning_: 6.67 miles. ~50-55 minutes. Easy/moderate pace. 1845 ft up, 1845 ft down. Third day running in a row. Which is a big deal lately. 🎉

_Evening_: 4.75 miles. Untimed. Need to not overdo it.

### 3/27/18

7.75 miles. Moderately hard at times. Untimed.

### 3/26/18

4.75 miles. Untimed.

### 3/25/18

11 mile hike.

### 3/23/18

4.75 miles. Untimed. Achilles pain subsided a bit after two miles.


### 3/21/18

4.75 miles. Untimed. I'm still in alright shape, but I haven't run in a couple weeks and I haven't done a structured workout in months. I decided on three goals this morning:

1. Local marathon in late-March 2019.
2. Sub-50 minutes for 10 miles
3. Log workouts

So here we are.


[footer fullWidth:true/]
