[menu fullWidth:true/]

[meta fullWidth:true title:"Running"/]

[Header
  title: "Running"
  fullWidth:true
  bgImageSrc:"images/CO2016-37.jpg"
/]

### 10/10/18

Haven't run since Saturday. Almost just bailed. Did a 10K on the track instead. 33:18 total (5:26-5:25-5:19-5:19-5:16-5:19-1:12). Felt great. Totally just cruising without excessive effort. Finished and wanted to do more.

### 10/6/18

Morning tempo. 5:28-5:26-5:22-5:26-5:23-5:19. Felt like a real grind, but held it together, so… a success?

### 10/3/18

Workout with the club. 5:12, 5:03, 5:01. Workoutmates finished with a 4:55. I stopped after three. Was tightening up. Wasn't gonna be able to hold a decent pace. Still content. It's slowly starting to feel more natural to run fast.

### 10/1/18

Lake loop. 6 miles. Easy/moderate. And some canine sprints.

### 9/30/18

Morning run in the hills. Took it pretty easy. 7 miles or so, maybe.

### 9/28/18

6am lake laps with the club and a mile or two with the little one. Big success to be getting out the door these days.

### 9/26/18

Track workout. 5 x 1 mile. 5:35, 5:28, 5:19, 5:14, 5:08. Definitely still dusting off the cobwebs (and still a little sore from long run) but maybe getting it back a little? I don't know. Still assuming most of the battle is just forcing it for now and then maybe it'll feel alright in another month or two.

### 9/23/18

Long run with the club. 16 miles total, I think? Some good hills in there. Pretty sore from it. Have started getting back into the long runs recently, but bringing back some effort was a nice change.

### 9/22/18

Another run with the track club. Lost count of the laps, but maybe 9-10 miles by the time I finished running with the canine. Knee is just a bit sore. Should probably back off before I hurt myself.

### 9/21/18

Solid workout with the local track club. Like fifteen miles by the time I did some sprint-n-sniffs with the furry one. 8 miles tempo-ish pace (5:45-5:55 maybe?). Felt pretty good, but gonna be a little sore and need some recovery after that.

### 9/20/18

Borderline workout. Two lake laps which amounts to about 8.75 total. No time on it, but I think it was mostly in the 5:45-6:00 min/mi range. So like not quite a proper workout, but sure felt good. Little sore. Otherwise feels great to be slowly getting back into it.

### 9/19/18

Workout. Fast tempo (with pee breaks) with the canine unit, then 2 x 1 mile on the track. 4:56, 4:56. Knee felt just fine. Encouraged that it didn't feel perfect but at least felt much better than it has been lately.

### 9/15/18

Workout. 4 x 1 mile with 400m moving rest. 5:29, 5:22, 5:17, 5:09. So it sped up at least, but certainly didn't feel easy like I hoped. Sometimes you just have to force it and wait for the day when it feels good. Hopefully.

### 9/12/18

Run with the dog and then 2 miles on the track (5:14-5:15). I conclude two things: 1) stopping abruptly to sniff trees is hard on human knees, and 2) I probably shouldn't start workouts with a dog-based tempo run if I want the track portion to be high-value.

### 9/11/18

Run with the dog. He's kickin' my butt. About 3 miles pretty hard.

### 9/10/18

Intended to do a track workout but woke up too late so just ran. 55 minutes or so. Maybe 8 miles? Tried to get it rolling toward the later section, with mixed success. I really shouldn't stray into the no-man's-land between easy runs and actual workouts, but when your training is generally kinda crap, go with it I guess 🤷🏻‍♂️.

### 9/8/18

[img src:"images/run.jpg" alt:"A run"/]

Long run. First in a loong time. 1:50. Maybe 2500 ft up and down. Feeling it this afternoon.

### 9/7/18

Blah run. Felt pretty horrible. Ballpark 5.5 miles maybe?

### 9/5/18

Track workout. 4 miles (5:28-5:29-5:29-5:25) + 1 mile (5:03). Had to force it, but wasn't entirely dissatisfied that I can at least still cruise around the track for a while, even if we've got a whole lot of work ahead in order to claw our way back. 10 miles total, give or take.

### 9/3/18

[img src:"images/clouds.jpg" alt:"Clouds"/]

77 minute run in the hills and with ~2000ft of elevation gain. Longest run in a while.

### 8/31/18

Morning run in the hills, followed with some brief but intense sprints with the dog. 1700ft up/down, which is always a plus. Feeling a bit more natural with a bit more regularity.

### 8/28/18

Hardly a workout. Couldn't bring myself to do a whole workout so just did a single mile on the track with just a bit of running. 4:57 for a mile. Didn't feel too bad, but still a struggle overall just to get out the door.

### 8/25/18

[img src:"images/rays.jpg" alt:"Anticrepuscular Rays"/]

A run in the hills with 1600ft up and down. A struggle lately to stay on the train and not just skip runs.

### 8/22/18

Some short runs in the mean time, but back on the track for an evening workout. 2 miles (5:22-5:26) + 1 mile (5:12). Wanted to do more. Still not feeling great, but I view it as getting the mediocre workouts out of the way so that we can get back to some good workouts.


### 8/16/18

A run with the dog, then a bit on the track and then 3 miles back home. 5K on the track in 16:51 (5:29, 5:24, 5:20, 0:38). I'm sore and this pace isn't feeling as easy as it needs to, but it's a good start just to be on the track at all.

### 8/15/18

Morning semi-run with the dog. Mostly sniffing.

### 8/14/18

[img src:"images/freycinet.jpg" alt:"Running"/]

Well we obviously haven't done a good job of logging the running here. We've had some pretty great runs and as much as a couple weeks without really much running at all. This hasn't been going according to plan, but then I guess the plan wasn't really to stick to a rigorous plan.

But today? Today was the first workout on a track in a long time. 10:19 for two miles (5:11-5:08). I'm a bit sore today but glad to know I can still move around a track at an alright speed. Going to try to repeat that soon.

### 4/5/18

2 x mile + 1 x 400. Short workout. 5:18, 5:15, 66. Feeling better than I thought maybe, but still not feeling particularly fast or effortless. Lots of work ahead if the Achilles will play along. 7 miles total.

### 4/3/18

3.17 mile tempo in 17:48 for an average pace of 5:36/mi. 4.75 miles total. Not bad. Good route. Room for consistent repetition and improvement.

### 4/1/18

6 mile hike. +/- 2400 ft.

### 3/31/18

5.5 miles. 3 x 1 mile on the track with 1:30 rest. 5:16, 5:17, 5:05. First thing approaching a workout in a long time. Nothing gets the lead out quite like the last 400m of your mile repeats coinciding with the first 600m of a high school team's workout. Didn't feel effortless, but maybe there's hope.

### 3/30/18

6.67 miles. Hill loop. 1845 ft up and down. 55:04 total. 24:25 up, 30:39 down.

### 3/29/18

8 miles. Moderate run with one mile on the track in the middle of the run. 5:17 (80-81-79-77). Felt tough. Knew getting the train started wasn't gonna be pleasant.

### 3/28/18

[img src:"images/el1.png" alt:"Elevation profile"/]

_Morning_: 6.67 miles. ~50-55 minutes. Easy/moderate pace. 1845 ft up, 1845 ft down. Third day running in a row. Which is a big deal lately. 🎉

_Evening_: 4.75 miles. Untimed. Need to not overdo it.

### 3/27/18

7.75 miles. Moderately hard at times. Untimed.

### 3/26/18

4.75 miles. Untimed.

### 3/25/18

11 mile hike.

### 3/23/18

4.75 miles. Untimed. Achilles pain subsided a bit after two miles.


### 3/21/18

4.75 miles. Untimed. I'm still in alright shape, but I haven't run in a couple weeks and I haven't done a structured workout in months. I decided on three goals this morning:

1. Local marathon in late-March 2019.
2. Sub-50 minutes for 10 miles
3. Log workouts

So here we are.


[footer fullWidth:true/]
