[menu fullWidth:true/]

[meta fullWidth:true title:"Running"/]

[Header
  title: "Running"
  fullWidth:true
  bgImageSrc:"images/CO2016-37.jpg"
/]

### 3/21/18

Lake run. 4.75 miles. Untimed. I'm still in alright shape, but I haven't run in a couple weeks and I haven't done a structured workout in months. I decided on three goals this morning:

1. Local marathon in late-March 2019.
2. Sub-50 minutes for 10 miles
3. Log workouts

So here we are.


[footer fullWidth:true/]
